# Generated by Django 4.2.7 on 2025-07-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_public',
        ),
    ]
