# Generated by Django 4.2.16 on 2025-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_achievement_shopitem_profile_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rating',
            field=models.IntegerField(blank=True, help_text="User's rating of the platform (1-5 stars)", null=True),
        ),
    ]
