# Generated by Django 4.2.16 on 2025-08-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_using_theme', to='accounts.shopitem'),
        ),
    ]
