# Generated by Django 4.2.16 on 2025-08-20 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_profile_selected_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('play_games', 'Play Games'), ('earn_points', 'Earn Points'), ('answer_correctly', 'Answer Correctly'), ('complete_quiz', 'Complete Quiz'), ('login_streak', 'Login Streak'), ('spend_coins', 'Spend Coins')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('reward_coins', models.IntegerField(default=10)),
                ('reward_points', models.IntegerField(default=50)),
                ('icon', models.CharField(default='fas fa-tasks', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['task_type', 'target_value'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('current_progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dailytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', 'is_completed'],
                'unique_together': {('user', 'task', 'assigned_date')},
            },
        ),
    ]
