# Generated by Django 4.2.16 on 2025-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dailytask_userdailytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
