# Generated by Django 4.2.7 on 2025-07-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_question_number',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='points_awarded',
        ),
        migrations.AddField(
            model_name='game',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_games', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
