# Generated by Django 4.2.1 on 2025-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_current_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_question_number',
            field=models.IntegerField(default=0),
        ),
    ]
