# Generated by Django 4.2.1 on 2025-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_current_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranswer',
            name='score_earned',
            field=models.IntegerField(default=0),
        ),
    ]
