# Generated by Django 4.2.1 on 2025-07-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_is_public'),
        ('game', '0004_playeranswer_score_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeranswer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
